apiVersion : apps/v1
kind: Deployment
metadata:
  name: azuredemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredemo
  template:
    metadata:
      labels:
        app: azuredemo 
    spec:
      containers:
        - name: azuredemo 
          image: azuretrianing.azurecr.io/azuredemo
          ports:
          - containerPort: 8080
