name: Push to Azure Blob Storage

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  push_to_azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Install Azure CLI
      uses: azure/setup-azure-cli@v1  # Install Azure CLI

    - name: Push files to Azure Blob Storage
      run: |
        az storage blob upload-batch --source . --destination <container-name> --account-name <storage-account-name> --sas-token ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
      env:
        AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}  # Pass SAS token as an environment variable
