name: Push to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  push_to_azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push files to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          pwd
          az storage blob upload-batch --source /home/runner/work/azure-demo/azure-demo --destination test1 --account-name brimmastorage --sas-token ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
